### PR TITLE
Add link to https://github.com/aviralpandey/CT-DS-ADC_generator

### PR DESCRIPTION
**Pull request by dan-fritchman**
Add link to https://github.com/aviralpandey/CT-DS-ADC_generator

A continuous-time delta-sigma ADC generator using [Hdl21](https://github.com/dan-fritchman/Hdl21) and [Vlsir](https://github.com/Vlsir/Vlsir).

### CODE REVIEW

**Comment by dan-fritchman** [comment]
Sorry we're late!

**Comment by msaligane** [comment]
@dan-fritchman, thanks for this contribution! Can you please send a PR with a folder under Notebooks and follow the notebook format? It is easier for the reviewers that way. 
Also, I will have to check with other reviewers. But since we are past the deadline, we might have to ask you to submit to the next code-a-chip competition (hopefully will communicate more info soon).

**Comment by dan-fritchman** [comment]
Hi Mehdi - 

It's a folder under `Notebooks/`, just provided via git submodule.  
Specifically `Notebooks/CT-DS-ADC_generator`. 
https://github.com/dan-fritchman/sscs-ose-code-a-chip.github.io/tree/main/Notebooks
The repo content will show up in full after running `git submodule update --init --recursive`, or similar. 

I see there's at least one merged submission using the same method, and perhaps a few more depending how they're organized.

**Comment by msaligane** [comment]
Hi Dan,

I am really sorry, but it was decided among reviewers that we will not review this work so that we can be fair to other submissions.
I really hope you can submit it again for the next code-a-chip.

One other quick note, please make sure you follow the template provided (authors list and some of the general formatting/documentation). I do not see it here: 
https://github.com/aviralpandey/CT-DS-ADC_generator/blob/6442f0bba48c7a1807e0d1e10b1bf53484f28dd7/Telescopic_Amplifier_Design.ipynb

**Pull request closed without merging**
