### PR TITLE
FVF Based  OTA

### PR DESCRIPTION
**Pull request by iitkgpshubham**

### CODE REVIEW

**Comment by msaligane** [comment]
5000+ files! @iitkgpshubham We only need your notebook.

**Comment by iitkgpshubham** [comment]
> 5000+ files! @iitkgpshubham We only need your notebook.

Extremely sorry... The simulation files were included which made it huge...
I have deleted them.... whatever left is just spice netlist files and sch... and drc, lvs results...

Let me know if you recommend to remove them as well...

@msaligane

**Comment by msaligane** [comment]
Only the notebook is needed.

**Comment by iitkgpshubham** [comment]
> Only the notebook is needed.

I have deleted the files. 
Only following are included, 
1. README.md
2. Notebook
3. `scripts` directory (Includes Sizing Notebooks, Glayout Pcell codes)

**Review by msaligane — APPROVED** [review]

**Pull request merged**
