### PR TITLE
Submission of Sobel filter OpenLane project

### PR DESCRIPTION
**Pull request by DianaNatali**

### CODE REVIEW

**Review by msaligane — APPROVED** [review]

**Comment by msaligane** [comment]
@DianaNatali You haven't provided any information about your affiliation, email contact or title.

**Comment by DianaNatali** [comment]
Email contact: dnmaldonador@unal.edu.co

**Comment by msaligane** [comment]
Thanks, can you provide a name and affiliation as well...

**Comment by msaligane** [comment]
@DianaNatali, you should probably update this in your notebook. Make sure to follow the template!

**Pull request merged**
