### PR TITLE
Bandgap Voltage Reference

### PR DESCRIPTION
**Pull request by johnkustin**
based on this repository: https://github.com/johnkustin/bandgapReferenceCircuit

### CODE REVIEW

**Comment by msaligane** [comment]
Due to multiple requests. We have decided to extend the deadline to the 25th Nov. so that, hopefully, you have enough time to review your submissions.

**Comment by msaligane** [comment]
@johnkustin Can you please resolve conflicts in this branch?

**Comment by johnkustin** [comment]
> @johnkustin Can you please resolve conflicts in this branch?

Done

**Comment by johnkustin** [comment]
i’m going to put “bandgap” in front of my files so they don’t confuse a new person to the repository

**Comment by johnkustin** [comment]
all done

**Comment by msaligane** [comment]
Thanks!

**Pull request merged**
