### PR TITLE
committing for code a chip 2025

### PR DESCRIPTION
**Pull request by alecadair**
submission for code a chip 2025

### CODE REVIEW

**Comment by msaligane** [comment]
@alecadair You have pushed over 5000+ files. We only need your notebook. Can you please fix this ASAP and add a readme of you want to reference your repo. Thanks!

**Comment by alecadair** [comment]
@msaligane will do. I understand 5,000 files is not acceptable for the submission, but am I able to have any files in addition to the notebook file? I.e. an images directory with some images, 5 or 6 files of external code to the notebook such as netlist template files? 

I am also working at my job today (Eastern European time zone) and unable to get a revised  in until about 18 hours from the time of this comment (6 AM EET). Thank you for reaching out.

**Comment by msaligane** [comment]
Images are fine. Sure, thanks!

**Comment by alecadair** [comment]
@msaligane I cleaned up the files and added references in README file. The thousands of files were generated from the flow itself and I had not cleaned them up on my last run. This notebook generates spice netlists, align netlists, extracted netlists, gds files for top level and all hierarchical cells, simulation data for ideal and extracted runs. With all of this the amount of files generated quickly adds up. I have included clean scripts as described remove data after generation.

In the README I have described the file structure now to be clear and descriptive of the files in the repository. Please take a look and please let me know if the repo is now acceptable. Thank you or letting me clean this up.

**Comment by msaligane** [comment]
Thanks! What are all the CSV files for, and can you keep everything self-contained in a notebook? 200+ files is still a lot!

**Comment by alecadair** [comment]
@msaligane The CSV files are lookup table files generated from device characterization over corners and temperature (-25, 25, and 75 C for tt, ff, and ss corners) which creates 9 files per device length . I do hope that I can keep these in the repository, but I can delete these and have a mandatory generation of them within the notebook. I have included them in case of a user pdk setup problems ngspice etc..

In the notebook I am only using 1 device length so perhaps I can get rid of the rest of the device CSV files that are not used - limiting the number of CSV files to only 9, even 3 if I just use typical corners as displayed in the graphs.

The rest of the scripts and files in the repository are mandatory. They are scripts for running the flow, template files for running the flow. I have tried to keep a clean and organized directory structure. What are your thoughts? For now I will get rid of all CSV characterization files that are not mandatory for the flow to run.

**Comment by msaligane** [comment]
Sounds good. Please remove the files that aren't mandatory and keep the notebook as self-contained as possible since it helps with the review. Thanks!

**Comment by alecadair** [comment]
I have removed those files. The file count is now at 160.. Perhaps what would be best is for me to move the flow with the external scripts, software, characterizations to a standalone repository which is then cloned from the notebook and referenced. Then that would leave this repo with only images and the notebook. Do you think this would be a better approach? Thanks for working with me on this as well, much appreciated.

**Comment by msaligane** [comment]
That would be great if it doesn't take a lot of time. I will check in my morning.

**Comment by alecadair** [comment]
@msaligane I will move the bulk of the code to a new repo and adjust the notebook accordingly - it should not too much time or be difficult. I will comment on here as well when the work is done.

**Comment by alecadair** [comment]
@msaligane the files are now referenced from an external repository that gets downloaded from the notebook.

**Comment by alecadair** [comment]
> That would be great if it doesn't take a lot of time. I will check in my morning.

@msaligane were you able to take a look at this? Sorry to bother you so much about this.. I am sure you are very busy as I believe today is the last day of review (according to official timeline on website).

**Pull request merged**
